name: app_kids
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts: ^4.0.4
  rive: ^0.9.1
  lottie: ^2.4.0
  audioplayers: ^4.1.0
  animated_background: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/figures/
    - assets/rivs/
    - assets/lottie/
    - assets/audio/
    - assets/core/
  
  fonts:
     - family: Patrick
       fonts:
         - asset: assets/fonts/PatrickHand-Regular.ttf         
           weight: 700

     - family: Pumpkin
       fonts:
         - asset: assets/fonts/Pumpkin.ttf 
           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
